import '@/styles/globals.css'

import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

import { Toaster } from '@/components/ui/sonner'
import { TRPCReactProvider } from '@/trpc/react'
import MainLayout from './_components/main-layout'

export const runtime = 'edge'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={`font-sans ${inter.variable}`}>
          <TRPCReactProvider>
            <MainLayout>
              {children}
              <Toaster />
            </MainLayout>
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
